### ISSUE TITLE
Error: Process exited before completing request

### ISSUE THREAD

**Issue by hlherrera** [awslabs/mxnet-lambda#2]
I have this error running a test:
/var/task/mxnet/module/base_module.py:64: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)

**Comment by David-Durst** [comment]
This should be fixed. Try the tip of master. See https://github.com/awslabs/mxnet-lambda/pull/5 for how it was fixed.
