### ISSUE TITLE
how to Compute the eigenvalues and eigenvectors of ndarray?

### ISSUE THREAD

**Issue by weihua04** [awslabs/mxnet-lambda#30]
i'd like to compute  the eigenvalues and eigenvectors of a hidden layer using mxnet, although i just know numpy can do this, i'm not sure mxnet have any methods to  compute  the eigenvalues and eigenvectors of a hidden layer,

thank u very much

**Comment by lanking520** [comment]
Please file this issue to https://github.com/apache/incubator-mxnet/issues, we can answer it there.
