### ISSUE TITLE
good job!  but will this waste a lot when reloading the model for every HTTP request?

### ISSUE THREAD

**Issue by 9crk** [awslabs/mxnet-lambda#8]
good job!  but will this waste a lot when reloading the model for every HTTP request?

seems it will load the model for every request, will it cause the delay? so is this really the right way doing this?

**Comment by sunilmallya-work** [comment]
It doesn't. variables outside the context handler arent' loaded on every request. check blog for more info https://aws.amazon.com/blogs/compute/seamlessly-scale-predictions-with-aws-lambda-and-mxnet/

**Comment by sunilmallya** [comment]
It doesn't. variables outside the context handler arent' loaded on every request. check blog for more info https://aws.amazon.com/blogs/compute/seamlessly-scale-predictions-with-aws-lambda-and-mxnet/

**Comment by 9crk** [comment]
wonderful!!! nice of you!
